sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
env:
  global:
  # Please get your own free key if you want to test yourself
  - BROWSERSTACK_USERNAME: dylanschiemann2
  - BROWSERSTACK_ACCESS_KEY: 4Q2g8YAc9qeZzB2hECnS
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - FORCE_COLOR: 1
script:
- npm run lint && npm run build:ci && npm run test:ci && npm run uploadCoverage
after_success:
- ./deploy.sh
